spring.application.name=sistemaAdopcion
spring.datasource.url=jdbc:mariadb://${URL_DB}
spring.datasource.username=${USER_DB}
spring.datasource.password=${PASSWORD_DB}
geocodio.api.key=${API_KEY_GEOCODIO}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${MAILTRAP_USERNAME}
spring.mail.password=${MAILTRAP_PASSWORD}
spring.mail.from=${MAILTRAP_FROM}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
